WordPressUI/Extensions/UIImageView+Networking.swift
Related to: https://github.com/wordpress-mobile/WordPress-iOS/issues/9296
This PR changes the code on 'downloadImage' to make sure any pending previous download on the UIImageView is cancelled even when we use the cache.
This solves the problem when an image url is initially set with a value that triggers a network call, then followed up by another url that is set using the cache. When the network callback executed the cache image that was set after was replaced by the older value.
=> Make sure previous download is canceled even if we go to cache.

WordPressUI/FancyAlert/FancyAlertView.swift
This PR introduces the same fix as https://github.com/wordpress-mobile/WordPress-iOS/pull/9471, but applied to WordPressUI now it's moved into a separate pod.
**To test:**
* Check out the `fix/fancy-alert-constraint` branch of WPiOS
* In WPiOS, update `needsEmailVerification` in `WPAccount` to `return true`
* Log in and open the editor, and add some text
* Tap Publish, then tap Resend on the alert that appears
* Without this patch, the app will crash. With the app, the fancy alert should transition to show new information and there should be no crash.
=> FancyAlertView: Make title accessory button constraint strong

WordPressUI/Extensions/UIImageView+Networking.swift
This PR fixes an issue described [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/9427#pullrequestreview-123300155) . 
> If I keep scrolling while still in airplane mode, some of the image views then switch into a loading state, even though they're not loading anything.
This happens because:
* When reusing cells, we always call `downloadImage` (for static ones).
* This triggers the loading state of the loading indicator.
* The loading indicator expect a success or an error to stop.
* When the download task finished with an error (in this case, no connection) ...
* If the reused cell is the same than before, the guard `guard url != downloadURL else {` will catch it.
* Since it used to just return, and the task is already finished, no success or error would be ever called.
* …
=> UIImageView+Networking: Fix no return point.

WordPressUI/Extensions/UIImageView+Networking.swift
Similar to #4 , there is another "no return point" when:
1. The url loading is the same than it was loading before.
2. The image was successfully downloaded.
This created the effect of showing the image and then changing to a infinite loading state.
This is easily reproducible having just one post with featured image in the post list.
This PR fixes this issue by:
- Getting a 'possible' cached image for the given url
- Checking if the url given is the same than before
- If that cached image exist, we can assume that the image was successfully downloaded previously
- Call the success block.
To test:
- Be sure to have just one post, and that post with a feature image.
- Open the post list and let the image load.
- Go back and open again the post list.
- Check that the image remains visible. …
=> UIImageView+Networking: Added missing success call

WordPressUI.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, WordPressUI/Extensions/UIImage+Assets.swift, WordPressUI/FancyAlert/FancyButton.swift
This PR removes the background image rendering method from FancyButton and adds it to the UIImage+Assets extension. It will be used in WordPressAuthenticator-iOS.
Change the WordPressUI pod to point to the new background image rendering extension branch `pod 'WordPressUI', :git => 'https://github.com/wordpress-mobile/WordPressUI-iOS.git', :branch => 'feature/extension-render-bg-image'`
This change helps support the implementation of a new feature in WordPressAuthenticator-iOS, [NUXButton configurable using UIAppearance](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/7)
cc: @jleandroperez
=> Move renderBackgroundImage() method out of `FancyButton` and into `UIImage+Assets` extension

WordPressUI/FancyAlert/FancyAlerts.storyboard
This is a small change that gives both buttons (cancel & default) in `FancyAlert` accessibility identifiers. It allows them to be addressed in UI tests.
I am making this change to help me move forward with fixing https://github.com/wordpress-mobile/WordPress-iOS/issues/9720.
=> Add accessibility identifiers to FancyAlert  buttons

WordPressUI/Extensions/UIImageView+Gravatar.swift, WordPressUI/Extensions/UIImageView+Networking.swift
This is the main changes to allow gravatar images to be updated in one place and take effect throughout the app.
Mostly: call `updateGravatar(image: UIImage, email: String?)` and it will post a `GravatarImageUpdateNotification` that all other UIImageViews displays the same gravatar will then display.
It's a bit of a hack, but it gets the job done and is _fairly_ easy to understand.
=> Add cache-breaking gravatar notification

WordPressUI.podspec, WordPressUI/Extensions/UIImageView+Gravatar.swift
Ok, let's see if this works better and less crashy:
Gravatar changes are still propagated with `NSNotification` but a wrapper is now used to remove the observer. @jleandroperez this is basically exactly as you suggested. How does it look?
=> Refactor UIImageGravatar+Gravatar to no longer crash

WordPressUI/Extensions/UIImageView+Gravatar.swift
Yeah, this removes two warnings.
and
I'd love to add the `@available(*, deprecated)` back in, but I ought to wait until `WPiOS` is ready to remove that call, and it's a touch _complicated_.
=> Fix some warnings in the Gravatar code

WordPressUI.podspec, WordPressUI/FancyAlert/FancyAlertView.swift, WordPressUI/FancyAlert/FancyAlertViewController.swift, WordPressUI/FancyAlert/FancyAlerts.storyboard
Adds a third button to the `FancyAlert`, which is required for Quick Start.
To test:
- in WPiOS, ensure that the existing alerts still work (prime for push after login or async alert after publishing first post)
- in WPiOS, on branch `issue/9447-add-never-to-QS-alert` ensure that there is a third button on the quick start alert, after creating a new `wpcom` site.
=> Add a third button to FancyAlerts

Example/Example.xcodeproj/project.pbxproj, Example/Example.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Example/Example.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Example/Example/AppDelegate.swift, Example/Example/Assets.xcassets/AppIcon.appiconset/Contents.json, Example/Example/Assets.xcassets/Contents.json, Example/Example/Base.lproj/LaunchScreen.storyboard, Example/Example/Base.lproj/Main.storyboard, Example/Example/Info.plist, Example/Example/ViewController.swift, Example/ExampleTests/ExampleTests.swift, Example/ExampleTests/Info.plist, Example/ExampleUITests/ExampleUITests.swift, Example/ExampleUITests/Info.plist, WordPressUI.xcworkspace/contents.xcworkspacedata, WordPressUI.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Adds an example App to WordPressUI.  It also includes a simple mechanism for extending the demos that we can offer, divided by sections.
This was copied almost verbatim from AztecExample, to avoid redoing any work.
Make sure there are no changes to the `WordPressUI` library itself, or to any file related to the library.  The idea is to make sure this change does not affect the library at all.
Open the workspace.
Build the library.  Make sure it builds fine.
Build and run the main app.  Make sure it builds fine and feel free to run the fancy alert demo.
=> Adds an example app for WordPressUI.

Example/Example.xcodeproj/project.pbxproj, Example/Example/ViewController.swift, WordPressUI/FancyAlert/FancyAlertView.swift, WordPressUI/FancyAlert/FancyAlertViewController.swift, WordPressUI/FancyAlert/FancyAlerts.storyboard
This PR adds an optional bottom switch to `FancyAlertView`.  This is intended to be used (at least initially) as a "Do not show this again" option for the alert.
Also adds 2 demos to showcase the "More information" button and the newly added switch.
Also fixes all unit tests.
Make sure the code looks fine.
Make sure the unit tests run fine.
Run the example App and:
- Open all 3 Fancy alert demos, and make sure they look fine.
- Try interacting with things and make sure an alert comes up describing your action.
=> Adds optional bottom switch to FancyAlertView

WordPressUI.podspec, WordPressUI/FancyAlert/FancyAlertView.swift, WordPressUI/FancyAlert/FancyAlertViewController.swift, WordPressUI/FancyAlert/FancyAlerts.storyboard
This PR makes the FancyAlert view scrollable when its content is taller than the screen height. This change is particularly useful for devices with small screens, for landscape usage, and bigger font sizes (accessibility).
I simplified the overall layout removing some unnecessary views and constraints, and added the scroll view inside the wrapper view, so the whole content is scrollable. At the same time, I made an effort to keep the previous layout, sizes and paddings, while making it look better with bigger text sizes.
I thought on leaving the buttons fixed at the bottom but it didn't play well in some scenarios, like many buttons with big text size on a small screen, or landscape mode.
I tested all the instances of the FancyView used on WPiOS that I found, them being:
- **Notification …
=> Making FancyAlert scrollable.

WordPressUI.podspec, WordPressUI/Extensions/UIImageView+Networking.swift
This PR improves the interface of the UIImageView+Networking extension by adding the following methods:
- cancelImageDownload
- downloadImageUsingRequest
It also makes the public methods available trough ObjC in order from them to be used on ObjC code on the main app.
This will allow the complete replacement of the AFNetworking uses on the main app, by using this extension.
=> Improve image view extensions

WordPressUI.podspec, WordPressUI.xcodeproj/project.pbxproj, WordPressUI/Extensions/NSBundle+ResourceBundle.swift, WordPressUI/Extensions/UIImage+Assets.swift, WordPressUI/FancyAlert/FancyAlertViewController.swift
This makes the changes needed for the WordPressUI pod to be installed as a static or dynamic framework (with or without `use_frameworks!`). Currently, it does not work correctly when installed statically.
The changes are as follows:
- Use `resource_bundles` to move resources to `WordPressUI.bundle`. This keeps the pod's resources separate from the main app.
- Replace all uses of `Bundle(for:..)`/`[NSBundle bundleForClass:]` with the new `Bundle. wordPressUIBundle` helper.
=> Compatibility with both CocoaPods dynamic and static frameworks

WordPressUI.xcodeproj/project.pbxproj, WordPressUI/Extensions/UIView+Helpers.swift, WordPressUITests/Extensions/UIView+ChangeLayoutMarginsTests.swift
This PR aims to add a new `UIView` helper called `changeLayoutMargins`.
By using it, you can change any `UIView`'s `layoutMargins` without the need to inform a complete `UIEdgeInsect`.
Instead of:
```
view.layoutMargins = UIEdgeInsets(top: view.layoutMargins.top, left: 5, bottom: view.layoutMargins.bottom, right: view.layoutMargins.right)
```
Just:
```
view.changeLayoutMargins(left: 5)
```
=> Adds changeLayoutMargins UIView helper

WordPressUI/Extensions/UIViewController+Helpers.swift
This is part of https://github.com/wordpress-mobile/WordPress-iOS/pull/11811.
This fixes false positives when the subject ViewController is “presenting” another ViewController.
=> isViewOnScreen: Detect presentedViewController

WordPressUI.podspec, WordPressUI.xcodeproj/project.pbxproj, WordPressUI/Extensions/UIView+Helpers.swift, WordPressUITests/Extensions/UIView+AutoLayoutHelperTests.swift
- WPiOS draft PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12293
- WCiOS draft PR: https://github.com/woocommerce/woocommerce-ios/pull/1170
- Added `insets: UIEdgeInsets` parameter to `pinSubviewToAllEdges(_ subview: UIView)`, and called this new function with zero insets in `pinSubviewToAllEdges(_ subview: UIView)`
- A separate function without `insets` parameter is necessary for Objective-C compatibility, otherwise we can set the default parameter of zero insets in the same function
- Created `pinSubviewToSafeArea(_ subview: UIView, insets: UIEdgeInsets)` and `pinSubviewToSafeArea(_ subview: UIView)` with zero insets
- Added basic tests for the above changes (lemme know if there is a better way to test this!)
=> Auto Layout helpers: add insets to edge pinning and safe area with insets

WordPressUI.podspec, WordPressUI/FancyAlert/FancyAlertView.swift, WordPressUI/FancyAlert/FancyAlerts.storyboard
This PR fixes the white background displayed in the Fancy Alerts on iOS 13 with Dark Mode enabled.
Refs. [#12320](https://github.com/wordpress-mobile/WordPress-iOS/issues/12320)
• Run [#12455](https://github.com/wordpress-mobile/WordPress-iOS/pull/12455)
=> [Dark Mode] Fix the Fancy Alert View background colors

Example/Example/Base.lproj/Main.storyboard, Example/Example/ViewController.swift, WordPressUI.podspec, WordPressUI/Extensions/UIImage+Assets.swift, WordPressUI/FancyAlert/FancyButton.swift
Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/12592.
This PR updates FancyButtons to have no drop shadow, and no border unless they're secondary buttons. I also added a new example screen to show the various fancy button styles.
The new styles are intended to look like this, however the colors in the example app won't match:
You can use [this WordPress iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12640) to verify in the WordPress app. You can also view the Fancy Buttons example in the example app.
=> Update fancy button border style

WordPressUI/FancyAlert/FancyAlertViewController.swift, WordPressUI/FancyAlert/FancyAlerts.storyboard
Fixes a bug in using accessibility identifiers with `FancyAlertView` buttons by applying them when the `FancyAlertView` is configured.
In some cases, they wouldn't be accessible the old way, where they were defined in the storyboard, but applying them from the code fixes this issue. It's _possible_ this could be related to the fact that the `never` and `cancel` buttons both used the same accessibility ID, but the error wasn't about an ambiguous element, it was about not being able to find it. In any case, now it's only applied to the cancel button.
Tests pass in both projects, so I think this is an ok approach. Let me know if you disagree?
**To Review**
- Ensure the code looks sensible
- Ensure that all tests pass in this PR, [as well as this …
=> Add accessibility identifiers for FancyAlertView

.circleci/config.yml, Example/Example.xcodeproj/project.pbxproj, WordPressUI.podspec, WordPressUI.xcodeproj/project.pbxproj
Fixes #54 
This PR:
- updates the Example project from Swift 4.2 -> 5.0
- updates the WordPressUI project from Swift 4.2 -> 5.0
- sets the CircleCI config from Xcode 10.2.0 -> Xcode 11.2.1 
- updates the podspec to version to 1.5.2-beta.1
- updates the podspec swift version to 5
- updates the ios version to 11.2.1
- ensure all CircleCI tests pass
=> Migrate to Swift 5

WordPressUI.podspec, WordPressUI/Extensions/UIImageView+Networking.swift
The image download URL was being improperly cached, preventing the image from being downloaded if there was a failure on the first try.
=> Fixes an issue with the image download URL being improperly cached.

WordPressUI.podspec, WordPressUI/Extensions/UIImageView+Networking.swift
Some images (e.g. the gravatar in the new 'Me' button) were not set at the first download, even if the image was cached
Test with [this](https://github.com/wordpress-mobile/WordPress-iOS/pull/13969) WordPress-iOS PR
=> Fixes issue: image not set at first download

WordPressUI.podspec, WordPressUI/FancyAlert/FancyButton.swift
**WPiOS**: https://github.com/wordpress-mobile/WordPress-iOS/pull/14042
This fixes an issue with FancyButton not responding to the `userInterfaceStyle` change. The background image used by the button does not automatically respond to the trait change (like a UIColor would), so this method refreshes that image.
- Check out and run the branch from https://github.com/wordpress-mobile/WordPress-iOS/pull/14042
- Verify that changing the appearance while the modal is shown properly changes the "Okay" button background.
| Before | After |
|--|--|
| ![FancyButtonBefore](https://user-images.githubusercontent.com/3250/80822631-5ffe1b80-8b98-11ea-8b7c-9c871d0e265c.gif) | ![FancyButtonAfter](https://user-images.githubusercontent.com/3250/80822639-642a3900-8b98-11ea-8733-55ac2438554d.gif) |
Otherwise, …
=> Change FancyButton background image w/ trait change
